@baseUrl = http://localhost:4000

###

GET {{baseUrl}}/books

###

POST {{baseUrl}}/books
Content-Type: application/json

{
  "title": "Livro 03",
  "description": "Descrição do livro 03",
  "pageAmount": 300
}

###

PUT {{baseUrl}}/books/0664ec9b-688e-45f5-97d2-3e376757a373
Content-Type: application/json

{
  "title": "Livro 04",
  "description": "Descrição do livro 04 (editado)",
  "pageAmount": 300
}

###

DELETE {{baseUrl}}/books/5e572671-04b2-4761-a4ac-d4a3a47ff50e
